spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
  rabbitmq:
    port: ${RABBIT_MQ_PORT:5672}
    host: ${HOST_RABBIT_MQ_PORT:localhost}

gate-way:
  host: ${GATE_WAY_HOST:http://localhost}
  port: ${GATE_WAY_PORT:8181}

grpc:
  port: ${GRPC_PRODUCT_PORT:9362}


rabbitmq:
  email:
    user-register-topic:
      routing:
        key: email.user.register
    delivery-register-topic:
      routing:
        key: email.delivery.register
    forgot-password-topic:
      routing:
        key: email.forgot_password
    exchange:
      name: email_topic_exchange

secure-internal:
  public-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKl5SroD9NuxQ955qCcCMERMAMJz2/CZfx3WTHkQa8cvf13FBkRFvRkLD7U1MRCNylxe+oebmy/OF4GzuSxcDl8CAwEAAQ=="
  private-key: "MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAqXlKugP027FD3nmoJwIwREwAwnPb8Jl/HdZMeRBrxy9/XcUGREW9GQsPtTUxEI3KXF76h5ubL84XgbO5LFwOXwIDAQABAkB7y8dDZFp8FNwv6oxjmlyptx8i7EEwWuAZao5ILS+duqnmZLLdSVpTF/tc58bFoBsZyWFru6sxmommxDipxwMBAiEA5FhOxbJeo8zn4OyASEzBuzWNv2QpEX7hpn5H9wlTVoECIQC9/7iLKBzB7YiS6+tKHRROHQt9n4OMcDGau5gfxXG03wIgRmGRpg3cbdByiDldMOu3quRO1Hci0WmyU4cI13PgZAECIEMMNbxtqFBLGXH3bO2Xe23hVAe9vbdWdDrNTm6Px4NzAiBjaQjKKLaSlP24wdaYe0cQxWuC0UlwAu5vHk0twRzV/g=="

expiration:
  verification: 604800
  password-reset: 900

encryption:
  key: Jf57xtfgC5X9tktm
server:
  port: ${USER_PORT:8888}
#  servlet:
#    context-path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:${EUREKA_PORT:8761}/eureka
springdoc:
  packagesToScan: latipe.user

