spring:
  application:
    name: websocket
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: "1.0"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: "true"