server:
  port: 8181
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
app:
  eureka-server: localhost
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: user_service
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: cart_service
          uri: http://localhost:7650
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: media_service
          uri: http://localhost:7657
          predicates:
            - Path=/api/v1/medias/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: product_service
          uri: http://localhost:8645
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: category_service
          uri: http://localhost:8645
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: attribute_service
          uri: http://localhost:8645
          predicates:
            - Path=/api/v1/attributes/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: search_service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/search/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: store_service
          uri: http://localhost:8118
          predicates:
            - Path=/api/v1/stores/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: payment_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payment/**
            - Path=/api/v1/payment-providers/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: paypal_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/paypal/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: discovery_server
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery_server_static
          uri: http://eureka:password@${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        - id: rating-service
          uri: http://localhost:8777
          predicates:
            - Path=/api/v1/ratings/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: orders-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: delivery-service
          uri: http://localhost:5005
          predicates:
            - Path=/api/v1/delivery/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: vouchers-service
          uri: http://localhost:5010
          predicates:
            - Path=/api/v1/vouchers/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

logging:
  #  level:
  #    org.springframework.web.HttpLogging: TRACE
  #    reactor.netty.http.server: DEBUG
  #    reactor.netty.http.client: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'

