global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "backoffice-bff"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["backoffice", "storefront"]

  - job_name: "product"
    metrics_path: "/product/actuator/prometheus"
    static_configs:
      - targets: ["product"]

  - job_name: "media"
    metrics_path: "/media/actuator/prometheus"
    static_configs:
      - targets: ["media"]
  - job_name: "rating"
    metrics_path: "/rating/actuator/prometheus"
    static_configs:
      - targets: ["rating"]
  - job_name: "order"
    metrics_path: "/order/actuator/prometheus"
    static_configs:
      - targets: ["order"]
  - job_name: "location"
    metrics_path: "/location/actuator/prometheus"
    static_configs:
      - targets: ["location"]
  - job_name: "inventory"
    metrics_path: "/inventory/actuator/prometheus"
    static_configs:
      - targets: ["inventory"]
  - job_name: "promotion"
    metrics_path: "/promotion/actuator/prometheus"
    static_configs:
      - targets: ["promotion"]
  - job_name: "tax"
    metrics_path: "/tax/actuator/prometheus"
    static_configs:
      - targets: ["tax"]
  - job_name: "payment"
    metrics_path: "/payment/actuator/prometheus"
    static_configs:
      - targets: ["payment"]
  - job_name: "payment-paypal"
    metrics_path: "/payment-paypal/actuator/prometheus"
    static_configs:
      - targets: ["payment-paypal"]
