spring:
  application:
    name: auth-service
  security:
    oauth2:
        resource-server:
          jwt:
            issuer-uri: http://localhost:8080/realms/latipe-realm
server:
  port: '8081'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: 'true'
      client-id: swagger-ui
    path: /swagger-ui
  oauthflow:
    token-url: http://localhost:8080/realms/latipe-realm/protocol/openid-connect/token
    authorization-url: http://localhost:8080/realms/latipe-realm/protocol/openid-connect/auth
  packagesToScan: latipe.auth