eureka:
  instance:
    hostname: localhost
  renewalPercentThreshold: '0.85'
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
spring:
  application:
    name: discovery-server
  security:
    user:
      password: ${EUREKA_PASSWORD:admin}
      name: ${EUREKA_USER:admin}
logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: ${EUREKA_PORT:8761}