spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/Latipe-Category-DB

server:
  port: '8118'
#  servlet:
#    context-path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
springdoc:
  swagger-ui:
    ocategory:
      use-pkce-with-categoryorization-code-grant: 'true'
      client-id: swagger-ui
    path: /swagger-ui
  ocategoryflow:
    token-url: http://localhost:8080/realms/latipe-realm/protocol/openid-connect/token
    categoryorization-url: http://localhost:8080/realms/latipe-realm/protocol/openid-connect/category
  packagesToScan: latipe.category

