spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/Latipe-Cart-DB

server:
  port: '7650'
#  servlet:
#    context-path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
springdoc:
  packagesToScan: latipe.cart

