spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/Latipe-Media-DB
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 125MB
      max-file-size: 125MB
server:
  port: '7657'
#  servlet:
#    context-path: /api/v1

# Cloudiary
cloudinary:
  api-key: 118683767447614
  api-secret: yXGR6ZXh9pjooT6EzKGfuBvqJQw
  cloud-name: dqe4dzug2

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
springdoc:
  packagesToScan: latipe.media

