spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/Latipe-Media-DB}
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 125MB
      max-file-size: 125MB
server:
    port: ${MEDIA_PORT:7657}
  #  servlet:
#    context-path: /api/v1

# Cloudiary
cloudinary:
  api-key: ${API_KEY:874849675994347}
  api-secret: ${API_SECRET:ub3xaoO8-A7j1pnT5NPFBLHvpeg}
  cloud-name: ${CLOUD_NAME:dj5jx4llf}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: '1.0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:${EUREKA_PORT:8761}/eureka
springdoc:
  packagesToScan: latipe.media

