server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"  # Explicitly define GRPC endpoint
        http:
          endpoint: "0.0.0.0:4318"  # Explicitly define HTTP endpoint

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    blocklist_poll: 5m           # How often to check for new blocks
    cache: memcached             # Use memcached for better performance
    memcached:
      consistent_hash: true
      host: memcached            # Point to memcached service
      service: memcached
      timeout: 500ms

compactor:
  compaction:
    block_retention: 48h         # Keep traces for 48 hours
    compacted_block_retention: 72h
  ring:
    kvstore:
      store: memberlist

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

search_enabled: true             # Enable search capability
