name: CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: latipe-rating-service
            directory: rating
          - service: latipe-store-service
            directory: store
          - service: latipe-search-service
            directory: search
          - service: latipe-product-service
            directory: product
          - service: latipe-discovery-server-service
            directory: discovery-server
          - service: latipe-cart-service
            directory: cart
          - service: latipe-api-gateway-service
            directory: api-gateway
          - service: latipe-media-service
            directory: media
          - service: latipe-user-service
            directory: user
          - service: latipe-auth-service
            directory: auth
          - service: latipe-payment-service
            directory: auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./${{ matrix.directory }}

      - name: Calculate new version
        id: calc_version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

          # Break down the tag into major, minor, patch
          IFS='.' read -ra version_parts <<< "$latest_tag"

          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}

          # Increment the patch version
          patch=$((patch + 1))

          # Construct the new tag
          new_tag="$major.$minor.$patch"

          # Set the new tag as an output variable
          echo "::set-output name=new_tag::$new_tag"

      - name: Build Docker image
        run: |
          VERSION=$(echo ${{ steps.calc_version.outputs.new_tag }})
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:$VERSION ./${{ matrix.directory }}

      - name: Push Docker image to Docker Hub
        run: |
          VERSION=$(echo ${{ steps.calc_version.outputs.new_tag }})
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:$VERSION

