name: CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: latipe-rating-service
            directory: rating
          - service: latipe-store-service
            directory: store
          - service: latipe-search-service
            directory: search
          - service: latipe-product-service
            directory: product
          - service: latipe-discovery-server-service
            directory: discovery-server
          - service: latipe-cart-service
            directory: cart
          - service: latipe-api-gateway-service
            directory: api-gateway
          - service: latipe-media-service
            directory: media
          - service: latipe-user-service
            directory: user
          - service: latipe-auth-service
            directory: auth
          - service: latipe-payment-service
            directory: auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.directory }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest